(lang dune 3.12)

(name myocamlproject)
(version 1.0.0)
(license MIT)

(generate_opam_files true)

(package
 (name myocamlproject)
 (synopsis "A test OCaml project")
 (depends
  ocaml
  (ocaml (>= "4.14"))
  dune
  (dune (>= "3.0"))
  (lwt (>= "5.6"))
  cohttp-lwt-unix
  yojson
  (ppx_deriving (>= "5.2"))))
